# These are for the database
database:
  # These usually don't need to be changed
  host: "localhost"
  port: "3306"
  # The name of your mysql database
  database: "auctionhouse"
  # The credentials to access the database
  username: "user"
  password: "pass"